[package]
name = "bincode"
version = "0.8.1"
authors = ["Ty Overby <ty@pre-alpha.com>", "Francesco Mazzoli <f@mazzo.li>", "David Tolnay <dtolnay@gmail.com>", "Daniel Griffen"]

# Adding ErrorKind::Invalid*Encoding is a breaking change
# Adding ErrorKind::DeserializeAnyNotSupported is a breaking change
publish = false

repository = "https://github.com/TyOverby/bincode"
documentation = "https://docs.rs/bincode"
keywords = ["binary", "encode", "decode", "serialize", "deserialize"]

license = "MIT"
description = "A binary serialization / deserialization strategy that uses Serde for transforming structs into bytes and vice versa!"

[dependencies]
byteorder = "1.0.0"
serde = "1.*.*"

[dev-dependencies]
serde_bytes = "0.10.*"
serde_derive = "1.*.*"
